# Generated by Django 5.1.6 on 2025-02-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0002_device_latitude_device_longitude_deviceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='logs',
            field=models.TextField(default='[]'),
        ),
    ]
