# Generated by Django 5.1.6 on 2025-02-13 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0003_device_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='logs',
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('log', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='agriculture.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
